name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    

jobs:
  test:
      runs-on: ubuntu-latest


      strategy:
        matrix:
          python-version: ["3.11", "3.12"]

      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v5
          with:
              python-version: ${{ matrix.python-version }}


        - name: Install Dependencies
          run: |
            pip install flake8 mypy pytest pytest-cov aiofiles types-aiofiles prometheus_client

        - name: Run flake8
          run: |
            flake8 . --max-line-length=120 --exclude=.venv --ignore=E265,W391,E231,E225,F401,E303,E261,E262,E712,W293,E266,E305,W291,E302,E301,E117,E111,E122,E271,E301,E302,E999,W292,E501,E203,E226,F541

        - name: Run mypy
          run: |
            mypy week2_PyDepth/storage_devoop.py

        - name: Run pytest
          run: |
            pytest week3_ToolsandInfra/test_StorageDevice.py --cov=week2_PyDepth --cov-report=term-missing